apiVersion: apps/v1
kind: Deployment
metadata:
  name: declab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: declab
  template:
    metadata:
      labels:
        app: declab
    spec:
      containers:
      - name: declab
        image: declab:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: declab
spec:
  selector:
    app: declab
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080