version: 2
jobs:
  # Build
  build_client:
    docker:
      - image: node:12.10.0-alpine
    environment:
      API_HOST: ./api
    steps:
      - checkout
      - run: cd ./declab/client && npm install && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  build_server:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd ./declab/server && mvn package
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  publish_release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ~/project
        - run: cd ./declab/server && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate -replace ${CIRCLE_TAG} ./target/declab-${CIRCLE_TAG}.war

  publish_container:
    docker:
      - image: ubuntu:18.04
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd ./declab/server && docker build --build-arg VERSION=${CIRCLE_TAG} -t maternase/declab:${CIRCLE_TAG} . && docker push maternase/declab:${CIRCLE_TAG}

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_client:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - build_server:
          requires:
            - build_client
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      #- publish_release:
      #    requires:
      #      - build_client
      #      - build_server
      #    filters:
      #      branches:
      #        ignore: /.*/
      #      tags:
      #        only: /.*/

      - publish_container:
          requires:
            - build_client
            - build_server
          filters:
            branches:
              only: /.*/ # TODO: ignore
            tags:
              only: /.*/