version: 2
jobs:
  build_client:
    docker:
      - image: node:12.10.0-alpine
    environment:
      API_HOST: ./api
    steps:
      - run: apk add --no-cache git
      - run: git clone https://github.com/materna-se/declab.git
      - run: cd ./declab/client && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  build_server:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd ./declab/server && mvn package
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  publish:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ~/project
        - run: cd ./declab/server && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate -replace 1.2.3 ./target/declab-1.2.3.war

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_client
      - build_server:
          requires:
            - build_client
      - publish:
          requires:
            - build_client
            - build_server