version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run: git clone https://github.com/materna-se/dmn-tester.git
      - run: git clone https://github.com/materna-se/jdec.git
      - run: cd ./jdec && mvn install -Dgpg.skip -Dmaven.javadoc.skip=true
      - run: cd ./dmn-tester/server && mvn test