version: 2
jobs:
  # Build
  build_client:
    docker:
      - image: circleci/node:12.10.0-stretch
    environment:
      API_HOST: ./api
    steps:
      - attach_workspace:
          at: ~/project
      - run: git clone https://github.com/materna-se/declab.git
      - run: cd ./declab/client && npm install && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  build_server:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd ./declab/server && mvn package
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./declab

  publish_release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ~/project
        - run: cd ./declab/server && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate -replace ${CIRCLE_TAG} ./target/declab-${CIRCLE_TAG}.war

  publish_container:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run: cd ./declab && docker login -u ${$DOCKER_USER} -p ${$DOCKER_PASSWORD} && docker build --build-arg VERSION=1.4.3 -t maternase/declab:1.4.3 . && docker push maternase/declab:1.4.3

workflows:
  version: 2
  build_and_publish:
    jobs:

      - publish_container:
          requires:
            - build_server
          filters:
            branches:
              only: /.*/ # TODO: ignore
            tags:
              only: /.*/