version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - run: pwd
      - run: ls
      - run: git clone https://github.com/materna-se/declab.git
      - run: git clone https://github.com/materna-se/jdec.git
      - run: cd ./jdec && mvn install -Dgpg.skip -Dmaven.javadoc.skip=true
      - run: cd ./declab/server && mvn package
      - run: pwd
      - run: ls
      - persist_to_workspace:
          root: ~/
          paths:
            - jdec
            - declab

  publish:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ~/
        - run: cd ./declab/server && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate -replace 1.2.3 ./target/declab-1.2.3.war

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build